version: '3.8'  # Verze Docker Compose

services:


  flask:  # Název služby pro Flask aplikaci
    container_name: web_flask  # Název kontejneru
    build:  # Specifikace pro sestavení obrazu
      context: ./app  # Adresář, kde Docker hledá Dockerfile a ostatní soubory
      dockerfile: Dockerfile_flask  # Název Dockerfile
    expose:
      - "5000"  # Interní port pro komunikaci mezi kontejnery
    volumes:
      - ./app:/usr/src/app  # Mapování místního adresáře do kontejneru pro případné změny v app ihned odstupné
    environment:
      FLASK_APP: run.py  # Flask aplikace bude hledat soubor run.py
      FLASK_RUN_HOST: 0.0.0.0  # Aplikace bude přístupná zvenčí kontejneru


  gunicorn:
    container_name: gunicorn
    build:
      context: ./app
      dockerfile: Dockerfile_gunicorn
    command: ["gunicorn", "--bind", "0.0.0.0:8000", "run:app"] # pro definici nebo úpravu image
    depends_on:
      - flask


  nginx: # Název
    container_name: nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80" # host:kontejner (host:kontejner)
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf  # Mapování konf. souboru pro okamžitou platnost
    depends_on:
      - gunicorn