version: '3.8'  # Verze Docker Compose

services:


  flask:  # Název služby pro Flask aplikaci
    container_name: web_flask  # Název kontejneru
    build:  # Specifikace pro sestavení obrazu
      context: ./app  # Adresář, kde Docker hledá Dockerfile a ostatní soubory
      dockerfile: Dockerfile_flask  # Název Dockerfile
    expose:
      - "5000"  # Interní port pro komunikaci mezi kontejnery
    volumes:
      - ./app:/usr/src/app  # Mapování místního adresáře do kontejneru pro případné změny v app ihned odstupné
    environment:
      FLASK_APP: run.py  # Flask aplikace bude hledat soubor run.py
      FLASK_RUN_HOST: 0.0.0.0  # Aplikace bude přístupná zvenčí kontejneru
    networks:
      - my_network # pro komunikaci mezi flaskem a databzi


  gunicorn:
    container_name: gunicorn
    build:
      context: ./app
      dockerfile: Dockerfile_gunicorn
    command: ["gunicorn", "--bind", "0.0.0.0:8000", "run:app"] # pro definici nebo úpravu image
    depends_on:
      - flask


  nginx: # Název
    container_name: nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80" # host:kontejner (host:kontejner)
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf  # Mapování konf. souboru pro okamžitou platnost
    depends_on:
      - gunicorn

  db:
    image: mysql:8.0  # Používá oficiální MySQL obraz verze 8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_password  # Nastaví heslo pro root uživatele
      MYSQL_DATABASE: my_database         # Vytvoří novou databázi
      MYSQL_USER: my_user                 # Vytvoří nového uživatele
      MYSQL_PASSWORD: my_password         # Nastaví heslo pro nového uživatele
    ports:
      - "3306:3306"                       # Mapuje port 3306 na hostitelský port 3306
    volumes:
      - db_data:/var/lib/mysql            # Persistentní úložiště pro data
    networks:
      - my_network                        # Síť, na které bude služba běžet

  adminer:
    image: adminer
    container_name: adminer
    ports:
      - "8080:8080"
    networks:
      - my_network

volumes:
  db_data:                               # Definuje přetrvájící volume ikdyž kontejner nebo images přestane existovat. Definice volume, Docker se postará o jeho vytvoření
                                         # cd /var/lib/docker/volumes/db_data/_data

networks:
  my_network:                            # Definuje síť ke které se mouhou připojovoat ostatní kontejnery